# -*- coding: utf-8 -*-
"""web_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cx3sVR2aXzcrVRObFhwkThtVNqHbYVVJ
"""

!pip install bs4
!pip install requests

from bs4 import BeautifulSoup as bs
import requests

HEADERS = ({'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
                           'Accept-Language': 'en-US, en;q=0.5'})

cust_name=[]
review_title=[]
review_date=[]
ratings=[]
review_content=[]

pages=list(range(0,446))
for i in pages:
    link='https://www.amazon.in/Apple-iPhone-Black-32GB-Storage/product-reviews/B01LZKSVRB/ref=cm_cr_getr_d_paging_btm_next_=?ie=UTF8&reviewerType=all_reviews&pageNumber='+str(i)
    request=requests.get(link,headers=HEADERS)
    soup=bs(request.content,'lxml')
    
    #extracting customer name
    names=soup.find_all("span",attrs={"class":"a-profile-name"})
    for j in range(0,len(names)):
        cust_name.append(names[j].get_text())
    
    #extracting review_title
    title=soup.find_all('a',attrs={"class":"review-title"})
    review_title=[]
    for j in range(0,len(title)):
        review_title.append(title[j].get_text())
        
    #extracting review_date
    date=soup.find_all("span",class_="a-size-base a-color-secondary review-date")
    for j in range(0,len(date)):
        review_date.append(date[j].get_text())
        
    # extracting review ratings
    rating=soup.find_all('i',class_='review-rating')
    for j in range(0,len(rating)):
        ratings.append(rating[j].get_text())
        
    # extracting reviews
    reviews=soup.find_all('span',{'data-hook':'review-body'})
    for j in range(0,len(reviews)):
        review_content.append(reviews[j].get_text())

review_title[:]=[titles.lstrip('\n') for titles in review_title]
review_title

review_title[:]=[titles.rstrip('\n') for titles in review_title]
review_title

review_date[:]=[date.lstrip('Reviewed in India on') for date in review_date]
#review_date

review_content[:]=[review.lstrip('\n') for review in review_content]
#review_content

review_content[:]=[review.rstrip('\n\n') for review in review_content]
#review_content

len(review_content)

import pandas as pd

df=pd.DataFrame()

df['Customer_name']=cust_name
#df['Review_title']=review_title
df['Reviewed_date']=review_date
df['Ratings']=ratings
#df['Reviews']=review_content

df

df1=pd.DataFrame()

df1['Reviews']=review_content

new = pd.concat([df,df1], ignore_index=False, axis=1)

new

df3=pd.DataFrame()

df3['Review_title']=review_title

new_data = pd.concat([new,df3], ignore_index=False, axis=1)

new_data

import pandas as pd
df = new_data.to_csv('reviews.csv', index = True)

df

